# Training Configuration
run = "dummy"
device_type = ""
depth = 10
max_seq_len = 2048
num_iterations = 5075
target_flops = -1.0
target_param_data_ratio = 20
device_batch_size = 8
total_batch_size = 524288
embedding_lr = 0.2
unembedding_lr = 0.004
weight_decay = 0.0
matrix_lr = 0.02
grad_clip = 1.0
warmup_ratio = 0.0
warmdown_ratio = 0.2
final_lr_frac = 0.0
resume_from_step = -1
eval_every = 250
eval_tokens = 10485760
core_metric_every = 2000
core_metric_max_per_task = 500
sample_every = 2000
save_every = -1
model_tag = ""
