# Training Configuration
run = "dummy"
device_type = ""
depth = 20
max_seq_len = 2048
num_iterations = 10000
target_param_data_ratio = 20
device_batch_size = 4
total_batch_size = 524288
embedding_lr = 0.2
unembedding_lr = 0.004
weight_decay = 0.0
matrix_lr = 0.01
grad_clip = 1.0
warmup_ratio = 0.0
warmdown_ratio = 0.2
final_lr_frac = 0.0
resume_from_step = -1
eval_every = 250
eval_tokens = 10485760
core_metric_every = 2000
core_metric_max_per_task = 500
sample_every = 2000
save_every = -1
model_tag = ""
approx_lm_head = true
lm_head_rank = 256
freeze_previous_weights = false
build_by_layer = false
mlp_proj_rank = 32
approx_attn = true
attn_rank = 48
gradient_checkpointing = false
